/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 11
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 26
#define ALIAS_COUNT 0
#define TOKEN_COUNT 16
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_unread_filter = 1,
  sym_read_filter = 2,
  sym_unread_feed = 3,
  sym_read_feed = 4,
  sym_unread_article = 5,
  sym_read_article = 6,
  anon_sym_COLON = 7,
  anon_sym_Feed = 8,
  anon_sym_Title = 9,
  anon_sym_Author = 10,
  anon_sym_Date = 11,
  anon_sym_Link = 12,
  sym_body_start = 13,
  sym_content = 14,
  sym__expression = 15,
  sym_nvimboat = 16,
  sym__element = 17,
  sym__filter = 18,
  sym__feed = 19,
  sym__article = 20,
  sym_header = 21,
  sym__header_line = 22,
  sym__header_key = 23,
  sym_body = 24,
  aux_sym_nvimboat_repeat1 = 25,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_unread_filter] = "unread_filter",
  [sym_read_filter] = "read_filter",
  [sym_unread_feed] = "unread_feed",
  [sym_read_feed] = "read_feed",
  [sym_unread_article] = "unread_article",
  [sym_read_article] = "read_article",
  [anon_sym_COLON] = ":",
  [anon_sym_Feed] = "Feed",
  [anon_sym_Title] = "Title",
  [anon_sym_Author] = "Author",
  [anon_sym_Date] = "Date",
  [anon_sym_Link] = "Link",
  [sym_body_start] = "body_start",
  [sym_content] = "content",
  [sym__expression] = "_expression",
  [sym_nvimboat] = "nvimboat",
  [sym__element] = "_element",
  [sym__filter] = "_filter",
  [sym__feed] = "_feed",
  [sym__article] = "_article",
  [sym_header] = "header",
  [sym__header_line] = "_header_line",
  [sym__header_key] = "_header_key",
  [sym_body] = "body",
  [aux_sym_nvimboat_repeat1] = "nvimboat_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_unread_filter] = sym_unread_filter,
  [sym_read_filter] = sym_read_filter,
  [sym_unread_feed] = sym_unread_feed,
  [sym_read_feed] = sym_read_feed,
  [sym_unread_article] = sym_unread_article,
  [sym_read_article] = sym_read_article,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_Feed] = anon_sym_Feed,
  [anon_sym_Title] = anon_sym_Title,
  [anon_sym_Author] = anon_sym_Author,
  [anon_sym_Date] = anon_sym_Date,
  [anon_sym_Link] = anon_sym_Link,
  [sym_body_start] = sym_body_start,
  [sym_content] = sym_content,
  [sym__expression] = sym__expression,
  [sym_nvimboat] = sym_nvimboat,
  [sym__element] = sym__element,
  [sym__filter] = sym__filter,
  [sym__feed] = sym__feed,
  [sym__article] = sym__article,
  [sym_header] = sym_header,
  [sym__header_line] = sym__header_line,
  [sym__header_key] = sym__header_key,
  [sym_body] = sym_body,
  [aux_sym_nvimboat_repeat1] = aux_sym_nvimboat_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_unread_filter] = {
    .visible = true,
    .named = true,
  },
  [sym_read_filter] = {
    .visible = true,
    .named = true,
  },
  [sym_unread_feed] = {
    .visible = true,
    .named = true,
  },
  [sym_read_feed] = {
    .visible = true,
    .named = true,
  },
  [sym_unread_article] = {
    .visible = true,
    .named = true,
  },
  [sym_read_article] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Feed] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Title] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Author] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Date] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Link] = {
    .visible = true,
    .named = false,
  },
  [sym_body_start] = {
    .visible = true,
    .named = true,
  },
  [sym_content] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_nvimboat] = {
    .visible = true,
    .named = true,
  },
  [sym__element] = {
    .visible = false,
    .named = true,
  },
  [sym__filter] = {
    .visible = false,
    .named = true,
  },
  [sym__feed] = {
    .visible = false,
    .named = true,
  },
  [sym__article] = {
    .visible = false,
    .named = true,
  },
  [sym_header] = {
    .visible = true,
    .named = true,
  },
  [sym__header_line] = {
    .visible = false,
    .named = true,
  },
  [sym__header_key] = {
    .visible = false,
    .named = true,
  },
  [sym_body] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_nvimboat_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(124);
      ADVANCE_MAP(
        ' ', 5,
        ':', 179,
        '=', 46,
        'A', 109,
        'D', 53,
        'F', 70,
        'L', 81,
        'N', 6,
        'T', 83,
      );
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(186);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(1);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(187);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        ' ', 5,
        ':', 179,
        '=', 46,
        'A', 109,
        'D', 53,
        'F', 70,
        'L', 81,
        'N', 6,
        'T', 83,
      );
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(3);
      END_STATE();
    case 4:
      ADVANCE_MAP(
        ' ', 4,
        '(', 116,
        ':', 179,
        '=', 46,
        'A', 109,
        'D', 53,
        'F', 70,
        'L', 81,
        'N', 6,
        'T', 83,
        0x2502, 24,
      );
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(3);
      END_STATE();
    case 5:
      ADVANCE_MAP(
        ' ', 4,
        ':', 179,
        '=', 46,
        'A', 109,
        'D', 53,
        'F', 70,
        'L', 81,
        'N', 6,
        'T', 83,
      );
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(3);
      END_STATE();
    case 6:
      if (lookahead == ' ') ADVANCE(40);
      END_STATE();
    case 7:
      if (lookahead == ' ') ADVANCE(48);
      END_STATE();
    case 8:
      if (lookahead == ' ') ADVANCE(49);
      END_STATE();
    case 9:
      if (lookahead == ' ') ADVANCE(19);
      if (lookahead == ':') ADVANCE(149);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(20);
      END_STATE();
    case 10:
      if (lookahead == ' ') ADVANCE(19);
      if (lookahead == 'e') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(20);
      END_STATE();
    case 11:
      if (lookahead == ' ') ADVANCE(19);
      if (lookahead == 'f') ADVANCE(12);
      if (lookahead == 'h') ADVANCE(18);
      if (lookahead == 0x2502) ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(20);
      END_STATE();
    case 12:
      if (lookahead == ' ') ADVANCE(19);
      if (lookahead == 'i') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(20);
      END_STATE();
    case 13:
      if (lookahead == ' ') ADVANCE(19);
      if (lookahead == 'l') ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(20);
      END_STATE();
    case 14:
      if (lookahead == ' ') ADVANCE(19);
      if (lookahead == 'p') ADVANCE(175);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(20);
      END_STATE();
    case 15:
      if (lookahead == ' ') ADVANCE(19);
      if (lookahead == 'r') ADVANCE(9);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(20);
      END_STATE();
    case 16:
      if (lookahead == ' ') ADVANCE(19);
      if (lookahead == 't') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(20);
      END_STATE();
    case 17:
      if (lookahead == ' ') ADVANCE(19);
      if (lookahead == 't') ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(20);
      END_STATE();
    case 18:
      if (lookahead == ' ') ADVANCE(19);
      if (lookahead == 't') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(20);
      END_STATE();
    case 19:
      if (lookahead == ' ') ADVANCE(19);
      if (lookahead == 0x2502) ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(20);
      END_STATE();
    case 20:
      if (lookahead == ' ') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(20);
      END_STATE();
    case 21:
      if (lookahead == ' ') ADVANCE(11);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(20);
      END_STATE();
    case 22:
      if (lookahead == ' ') ADVANCE(51);
      END_STATE();
    case 23:
      if (lookahead == ' ') ADVANCE(47);
      END_STATE();
    case 24:
      if (lookahead == ' ') ADVANCE(119);
      END_STATE();
    case 25:
      if (lookahead == ' ') ADVANCE(50);
      END_STATE();
    case 26:
      if (lookahead == ' ') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(39);
      END_STATE();
    case 27:
      if (lookahead == ' ') ADVANCE(121);
      END_STATE();
    case 28:
      if (lookahead == ' ') ADVANCE(38);
      if (lookahead == ':') ADVANCE(136);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(39);
      END_STATE();
    case 29:
      if (lookahead == ' ') ADVANCE(38);
      if (lookahead == 'e') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(39);
      END_STATE();
    case 30:
      if (lookahead == ' ') ADVANCE(38);
      if (lookahead == 'f') ADVANCE(31);
      if (lookahead == 'h') ADVANCE(36);
      if (lookahead == 0x2502) ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(39);
      END_STATE();
    case 31:
      if (lookahead == ' ') ADVANCE(38);
      if (lookahead == 'i') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(39);
      END_STATE();
    case 32:
      if (lookahead == ' ') ADVANCE(38);
      if (lookahead == 'l') ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(39);
      END_STATE();
    case 33:
      if (lookahead == ' ') ADVANCE(38);
      if (lookahead == 'p') ADVANCE(162);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(39);
      END_STATE();
    case 34:
      if (lookahead == ' ') ADVANCE(38);
      if (lookahead == 'r') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(39);
      END_STATE();
    case 35:
      if (lookahead == ' ') ADVANCE(38);
      if (lookahead == 't') ADVANCE(33);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(39);
      END_STATE();
    case 36:
      if (lookahead == ' ') ADVANCE(38);
      if (lookahead == 't') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(39);
      END_STATE();
    case 37:
      if (lookahead == ' ') ADVANCE(38);
      if (lookahead == 't') ADVANCE(29);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(39);
      END_STATE();
    case 38:
      if (lookahead == ' ') ADVANCE(38);
      if (lookahead == 0x2502) ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(39);
      END_STATE();
    case 39:
      if (lookahead == ' ') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(39);
      END_STATE();
    case 40:
      if (lookahead == '(') ADVANCE(123);
      if (lookahead == 0x2502) ADVANCE(27);
      END_STATE();
    case 41:
      if (lookahead == ')') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      END_STATE();
    case 42:
      if (lookahead == ')') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 43:
      if (lookahead == '/') ADVANCE(117);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      END_STATE();
    case 44:
      if (lookahead == '/') ADVANCE(122);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(44);
      END_STATE();
    case 45:
      if (lookahead == '=') ADVANCE(185);
      END_STATE();
    case 46:
      if (lookahead == '=') ADVANCE(7);
      END_STATE();
    case 47:
      if (lookahead == '=') ADVANCE(45);
      END_STATE();
    case 48:
      if (lookahead == 'A') ADVANCE(102);
      END_STATE();
    case 49:
      ADVANCE_MAP(
        'A', 97,
        'D', 73,
        'F', 68,
        'J', 54,
        'M', 52,
        'N', 92,
        'O', 61,
        'S', 69,
      );
      END_STATE();
    case 50:
      ADVANCE_MAP(
        'A', 98,
        'D', 75,
        'F', 71,
        'J', 56,
        'M', 55,
        'N', 94,
        'O', 62,
        'S', 72,
      );
      END_STATE();
    case 51:
      if (lookahead == 'B') ADVANCE(74);
      END_STATE();
    case 52:
      if (lookahead == 'a') ADVANCE(114);
      END_STATE();
    case 53:
      if (lookahead == 'a') ADVANCE(107);
      END_STATE();
    case 54:
      if (lookahead == 'a') ADVANCE(89);
      if (lookahead == 'u') ADVANCE(112);
      END_STATE();
    case 55:
      if (lookahead == 'a') ADVANCE(115);
      END_STATE();
    case 56:
      if (lookahead == 'a') ADVANCE(90);
      if (lookahead == 'u') ADVANCE(113);
      END_STATE();
    case 57:
      if (lookahead == 'b') ADVANCE(178);
      END_STATE();
    case 58:
      if (lookahead == 'b') ADVANCE(177);
      END_STATE();
    case 59:
      if (lookahead == 'c') ADVANCE(178);
      END_STATE();
    case 60:
      if (lookahead == 'c') ADVANCE(177);
      END_STATE();
    case 61:
      if (lookahead == 'c') ADVANCE(105);
      END_STATE();
    case 62:
      if (lookahead == 'c') ADVANCE(106);
      END_STATE();
    case 63:
      if (lookahead == 'c') ADVANCE(87);
      END_STATE();
    case 64:
      if (lookahead == 'd') ADVANCE(180);
      END_STATE();
    case 65:
      if (lookahead == 'e') ADVANCE(64);
      END_STATE();
    case 66:
      if (lookahead == 'e') ADVANCE(183);
      END_STATE();
    case 67:
      if (lookahead == 'e') ADVANCE(181);
      END_STATE();
    case 68:
      if (lookahead == 'e') ADVANCE(57);
      END_STATE();
    case 69:
      if (lookahead == 'e') ADVANCE(95);
      END_STATE();
    case 70:
      if (lookahead == 'e') ADVANCE(65);
      END_STATE();
    case 71:
      if (lookahead == 'e') ADVANCE(58);
      END_STATE();
    case 72:
      if (lookahead == 'e') ADVANCE(96);
      END_STATE();
    case 73:
      if (lookahead == 'e') ADVANCE(59);
      END_STATE();
    case 74:
      if (lookahead == 'e') ADVANCE(79);
      END_STATE();
    case 75:
      if (lookahead == 'e') ADVANCE(60);
      END_STATE();
    case 76:
      if (lookahead == 'e') ADVANCE(22);
      END_STATE();
    case 77:
      if (lookahead == 'g') ADVANCE(178);
      END_STATE();
    case 78:
      if (lookahead == 'g') ADVANCE(177);
      END_STATE();
    case 79:
      if (lookahead == 'g') ADVANCE(84);
      END_STATE();
    case 80:
      if (lookahead == 'h') ADVANCE(93);
      END_STATE();
    case 81:
      if (lookahead == 'i') ADVANCE(88);
      END_STATE();
    case 82:
      if (lookahead == 'i') ADVANCE(63);
      END_STATE();
    case 83:
      if (lookahead == 'i') ADVANCE(104);
      END_STATE();
    case 84:
      if (lookahead == 'i') ADVANCE(91);
      END_STATE();
    case 85:
      if (lookahead == 'k') ADVANCE(184);
      END_STATE();
    case 86:
      if (lookahead == 'l') ADVANCE(67);
      END_STATE();
    case 87:
      if (lookahead == 'l') ADVANCE(76);
      END_STATE();
    case 88:
      if (lookahead == 'n') ADVANCE(85);
      END_STATE();
    case 89:
      if (lookahead == 'n') ADVANCE(178);
      END_STATE();
    case 90:
      if (lookahead == 'n') ADVANCE(177);
      END_STATE();
    case 91:
      if (lookahead == 'n') ADVANCE(23);
      END_STATE();
    case 92:
      if (lookahead == 'o') ADVANCE(110);
      END_STATE();
    case 93:
      if (lookahead == 'o') ADVANCE(99);
      END_STATE();
    case 94:
      if (lookahead == 'o') ADVANCE(111);
      END_STATE();
    case 95:
      if (lookahead == 'p') ADVANCE(178);
      END_STATE();
    case 96:
      if (lookahead == 'p') ADVANCE(177);
      END_STATE();
    case 97:
      if (lookahead == 'p') ADVANCE(100);
      if (lookahead == 'u') ADVANCE(77);
      END_STATE();
    case 98:
      if (lookahead == 'p') ADVANCE(101);
      if (lookahead == 'u') ADVANCE(78);
      END_STATE();
    case 99:
      if (lookahead == 'r') ADVANCE(182);
      END_STATE();
    case 100:
      if (lookahead == 'r') ADVANCE(178);
      END_STATE();
    case 101:
      if (lookahead == 'r') ADVANCE(177);
      END_STATE();
    case 102:
      if (lookahead == 'r') ADVANCE(108);
      END_STATE();
    case 103:
      if (lookahead == 't') ADVANCE(80);
      END_STATE();
    case 104:
      if (lookahead == 't') ADVANCE(86);
      END_STATE();
    case 105:
      if (lookahead == 't') ADVANCE(178);
      END_STATE();
    case 106:
      if (lookahead == 't') ADVANCE(177);
      END_STATE();
    case 107:
      if (lookahead == 't') ADVANCE(66);
      END_STATE();
    case 108:
      if (lookahead == 't') ADVANCE(82);
      END_STATE();
    case 109:
      if (lookahead == 'u') ADVANCE(103);
      END_STATE();
    case 110:
      if (lookahead == 'v') ADVANCE(178);
      END_STATE();
    case 111:
      if (lookahead == 'v') ADVANCE(177);
      END_STATE();
    case 112:
      if (lookahead == 'l' ||
          lookahead == 'n') ADVANCE(178);
      END_STATE();
    case 113:
      if (lookahead == 'l' ||
          lookahead == 'n') ADVANCE(177);
      END_STATE();
    case 114:
      if (lookahead == 'r' ||
          lookahead == 'y') ADVANCE(178);
      END_STATE();
    case 115:
      if (lookahead == 'r' ||
          lookahead == 'y') ADVANCE(177);
      END_STATE();
    case 116:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      END_STATE();
    case 117:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      END_STATE();
    case 118:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      END_STATE();
    case 119:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(118);
      END_STATE();
    case 120:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      END_STATE();
    case 121:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(120);
      END_STATE();
    case 122:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 123:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(44);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym_unread_filter);
      if (lookahead == ' ') ADVANCE(135);
      if (lookahead == ':') ADVANCE(136);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(136);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(sym_unread_filter);
      if (lookahead == ' ') ADVANCE(135);
      if (lookahead == 'e') ADVANCE(131);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(136);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym_unread_filter);
      if (lookahead == ' ') ADVANCE(135);
      if (lookahead == 'f') ADVANCE(128);
      if (lookahead == 'h') ADVANCE(134);
      if (lookahead == 0x2502) ADVANCE(137);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(136);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(sym_unread_filter);
      if (lookahead == ' ') ADVANCE(135);
      if (lookahead == 'i') ADVANCE(129);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(136);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(sym_unread_filter);
      if (lookahead == ' ') ADVANCE(135);
      if (lookahead == 'l') ADVANCE(133);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(136);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(sym_unread_filter);
      if (lookahead == ' ') ADVANCE(135);
      if (lookahead == 'p') ADVANCE(136);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(136);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(sym_unread_filter);
      if (lookahead == ' ') ADVANCE(135);
      if (lookahead == 'r') ADVANCE(125);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(136);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym_unread_filter);
      if (lookahead == ' ') ADVANCE(135);
      if (lookahead == 't') ADVANCE(130);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(136);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym_unread_filter);
      if (lookahead == ' ') ADVANCE(135);
      if (lookahead == 't') ADVANCE(126);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(136);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_unread_filter);
      if (lookahead == ' ') ADVANCE(135);
      if (lookahead == 't') ADVANCE(132);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(136);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(sym_unread_filter);
      if (lookahead == ' ') ADVANCE(135);
      if (lookahead == 0x2502) ADVANCE(137);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(136);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(sym_unread_filter);
      if (lookahead == ' ') ADVANCE(135);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(136);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(sym_unread_filter);
      if (lookahead == ' ') ADVANCE(127);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(136);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(sym_read_filter);
      if (lookahead == ' ') ADVANCE(148);
      if (lookahead == ':') ADVANCE(149);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(149);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(sym_read_filter);
      if (lookahead == ' ') ADVANCE(148);
      if (lookahead == 'e') ADVANCE(144);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(149);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(sym_read_filter);
      if (lookahead == ' ') ADVANCE(148);
      if (lookahead == 'f') ADVANCE(141);
      if (lookahead == 'h') ADVANCE(147);
      if (lookahead == 0x2502) ADVANCE(150);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(149);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(sym_read_filter);
      if (lookahead == ' ') ADVANCE(148);
      if (lookahead == 'i') ADVANCE(142);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(149);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(sym_read_filter);
      if (lookahead == ' ') ADVANCE(148);
      if (lookahead == 'l') ADVANCE(146);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(149);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(sym_read_filter);
      if (lookahead == ' ') ADVANCE(148);
      if (lookahead == 'p') ADVANCE(149);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(149);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(sym_read_filter);
      if (lookahead == ' ') ADVANCE(148);
      if (lookahead == 'r') ADVANCE(138);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(149);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(sym_read_filter);
      if (lookahead == ' ') ADVANCE(148);
      if (lookahead == 't') ADVANCE(143);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(149);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(sym_read_filter);
      if (lookahead == ' ') ADVANCE(148);
      if (lookahead == 't') ADVANCE(139);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(149);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(sym_read_filter);
      if (lookahead == ' ') ADVANCE(148);
      if (lookahead == 't') ADVANCE(145);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(149);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(sym_read_filter);
      if (lookahead == ' ') ADVANCE(148);
      if (lookahead == 0x2502) ADVANCE(150);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(149);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(sym_read_filter);
      if (lookahead == ' ') ADVANCE(148);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(149);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(sym_read_filter);
      if (lookahead == ' ') ADVANCE(140);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(149);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(sym_unread_feed);
      if (lookahead == ' ') ADVANCE(161);
      if (lookahead == ':') ADVANCE(136);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(162);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(sym_unread_feed);
      if (lookahead == ' ') ADVANCE(161);
      if (lookahead == 'e') ADVANCE(157);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(162);
      END_STATE();
    case 153:
      ACCEPT_TOKEN(sym_unread_feed);
      if (lookahead == ' ') ADVANCE(161);
      if (lookahead == 'f') ADVANCE(154);
      if (lookahead == 'h') ADVANCE(160);
      if (lookahead == 0x2502) ADVANCE(163);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(162);
      END_STATE();
    case 154:
      ACCEPT_TOKEN(sym_unread_feed);
      if (lookahead == ' ') ADVANCE(161);
      if (lookahead == 'i') ADVANCE(155);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(162);
      END_STATE();
    case 155:
      ACCEPT_TOKEN(sym_unread_feed);
      if (lookahead == ' ') ADVANCE(161);
      if (lookahead == 'l') ADVANCE(159);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(162);
      END_STATE();
    case 156:
      ACCEPT_TOKEN(sym_unread_feed);
      if (lookahead == ' ') ADVANCE(161);
      if (lookahead == 'p') ADVANCE(162);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(162);
      END_STATE();
    case 157:
      ACCEPT_TOKEN(sym_unread_feed);
      if (lookahead == ' ') ADVANCE(161);
      if (lookahead == 'r') ADVANCE(151);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(162);
      END_STATE();
    case 158:
      ACCEPT_TOKEN(sym_unread_feed);
      if (lookahead == ' ') ADVANCE(161);
      if (lookahead == 't') ADVANCE(156);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(162);
      END_STATE();
    case 159:
      ACCEPT_TOKEN(sym_unread_feed);
      if (lookahead == ' ') ADVANCE(161);
      if (lookahead == 't') ADVANCE(152);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(162);
      END_STATE();
    case 160:
      ACCEPT_TOKEN(sym_unread_feed);
      if (lookahead == ' ') ADVANCE(161);
      if (lookahead == 't') ADVANCE(158);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(162);
      END_STATE();
    case 161:
      ACCEPT_TOKEN(sym_unread_feed);
      if (lookahead == ' ') ADVANCE(161);
      if (lookahead == 0x2502) ADVANCE(163);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(162);
      END_STATE();
    case 162:
      ACCEPT_TOKEN(sym_unread_feed);
      if (lookahead == ' ') ADVANCE(161);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(162);
      END_STATE();
    case 163:
      ACCEPT_TOKEN(sym_unread_feed);
      if (lookahead == ' ') ADVANCE(153);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(162);
      END_STATE();
    case 164:
      ACCEPT_TOKEN(sym_read_feed);
      if (lookahead == ' ') ADVANCE(174);
      if (lookahead == ':') ADVANCE(149);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(175);
      END_STATE();
    case 165:
      ACCEPT_TOKEN(sym_read_feed);
      if (lookahead == ' ') ADVANCE(174);
      if (lookahead == 'e') ADVANCE(170);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(175);
      END_STATE();
    case 166:
      ACCEPT_TOKEN(sym_read_feed);
      if (lookahead == ' ') ADVANCE(174);
      if (lookahead == 'f') ADVANCE(167);
      if (lookahead == 'h') ADVANCE(173);
      if (lookahead == 0x2502) ADVANCE(176);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(175);
      END_STATE();
    case 167:
      ACCEPT_TOKEN(sym_read_feed);
      if (lookahead == ' ') ADVANCE(174);
      if (lookahead == 'i') ADVANCE(168);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(175);
      END_STATE();
    case 168:
      ACCEPT_TOKEN(sym_read_feed);
      if (lookahead == ' ') ADVANCE(174);
      if (lookahead == 'l') ADVANCE(172);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(175);
      END_STATE();
    case 169:
      ACCEPT_TOKEN(sym_read_feed);
      if (lookahead == ' ') ADVANCE(174);
      if (lookahead == 'p') ADVANCE(175);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(175);
      END_STATE();
    case 170:
      ACCEPT_TOKEN(sym_read_feed);
      if (lookahead == ' ') ADVANCE(174);
      if (lookahead == 'r') ADVANCE(164);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(175);
      END_STATE();
    case 171:
      ACCEPT_TOKEN(sym_read_feed);
      if (lookahead == ' ') ADVANCE(174);
      if (lookahead == 't') ADVANCE(169);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(175);
      END_STATE();
    case 172:
      ACCEPT_TOKEN(sym_read_feed);
      if (lookahead == ' ') ADVANCE(174);
      if (lookahead == 't') ADVANCE(165);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(175);
      END_STATE();
    case 173:
      ACCEPT_TOKEN(sym_read_feed);
      if (lookahead == ' ') ADVANCE(174);
      if (lookahead == 't') ADVANCE(171);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(175);
      END_STATE();
    case 174:
      ACCEPT_TOKEN(sym_read_feed);
      if (lookahead == ' ') ADVANCE(174);
      if (lookahead == 0x2502) ADVANCE(176);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(175);
      END_STATE();
    case 175:
      ACCEPT_TOKEN(sym_read_feed);
      if (lookahead == ' ') ADVANCE(174);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(175);
      END_STATE();
    case 176:
      ACCEPT_TOKEN(sym_read_feed);
      if (lookahead == ' ') ADVANCE(166);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(175);
      END_STATE();
    case 177:
      ACCEPT_TOKEN(sym_unread_article);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(177);
      END_STATE();
    case 178:
      ACCEPT_TOKEN(sym_read_article);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(178);
      END_STATE();
    case 179:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 180:
      ACCEPT_TOKEN(anon_sym_Feed);
      END_STATE();
    case 181:
      ACCEPT_TOKEN(anon_sym_Title);
      END_STATE();
    case 182:
      ACCEPT_TOKEN(anon_sym_Author);
      END_STATE();
    case 183:
      ACCEPT_TOKEN(anon_sym_Date);
      END_STATE();
    case 184:
      ACCEPT_TOKEN(anon_sym_Link);
      END_STATE();
    case 185:
      ACCEPT_TOKEN(sym_body_start);
      END_STATE();
    case 186:
      ACCEPT_TOKEN(sym_content);
      if (lookahead == '\n') ADVANCE(186);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(1);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 187:
      ACCEPT_TOKEN(sym_content);
      if (lookahead == '\n') ADVANCE(187);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 188:
      ACCEPT_TOKEN(sym__expression);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(188);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(189);
      END_STATE();
    case 189:
      ACCEPT_TOKEN(sym__expression);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(189);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 188},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_unread_filter] = ACTIONS(1),
    [sym_read_filter] = ACTIONS(1),
    [sym_unread_feed] = ACTIONS(1),
    [sym_read_feed] = ACTIONS(1),
    [sym_unread_article] = ACTIONS(1),
    [sym_read_article] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_Feed] = ACTIONS(1),
    [anon_sym_Title] = ACTIONS(1),
    [anon_sym_Author] = ACTIONS(1),
    [anon_sym_Date] = ACTIONS(1),
    [anon_sym_Link] = ACTIONS(1),
    [sym_body_start] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_nvimboat] = STATE(8),
    [sym__element] = STATE(2),
    [sym__filter] = STATE(2),
    [sym__feed] = STATE(2),
    [sym__article] = STATE(2),
    [sym_header] = STATE(2),
    [sym__header_line] = STATE(4),
    [sym__header_key] = STATE(9),
    [sym_body] = STATE(2),
    [aux_sym_nvimboat_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_unread_filter] = ACTIONS(5),
    [sym_read_filter] = ACTIONS(5),
    [sym_unread_feed] = ACTIONS(7),
    [sym_read_feed] = ACTIONS(7),
    [sym_unread_article] = ACTIONS(5),
    [sym_read_article] = ACTIONS(5),
    [anon_sym_Feed] = ACTIONS(9),
    [anon_sym_Title] = ACTIONS(9),
    [anon_sym_Author] = ACTIONS(9),
    [anon_sym_Date] = ACTIONS(9),
    [anon_sym_Link] = ACTIONS(9),
    [sym_body_start] = ACTIONS(11),
  },
  [STATE(2)] = {
    [sym__element] = STATE(3),
    [sym__filter] = STATE(3),
    [sym__feed] = STATE(3),
    [sym__article] = STATE(3),
    [sym_header] = STATE(3),
    [sym__header_line] = STATE(4),
    [sym__header_key] = STATE(9),
    [sym_body] = STATE(3),
    [aux_sym_nvimboat_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(13),
    [sym_unread_filter] = ACTIONS(15),
    [sym_read_filter] = ACTIONS(15),
    [sym_unread_feed] = ACTIONS(17),
    [sym_read_feed] = ACTIONS(17),
    [sym_unread_article] = ACTIONS(15),
    [sym_read_article] = ACTIONS(15),
    [anon_sym_Feed] = ACTIONS(9),
    [anon_sym_Title] = ACTIONS(9),
    [anon_sym_Author] = ACTIONS(9),
    [anon_sym_Date] = ACTIONS(9),
    [anon_sym_Link] = ACTIONS(9),
    [sym_body_start] = ACTIONS(11),
  },
  [STATE(3)] = {
    [sym__element] = STATE(3),
    [sym__filter] = STATE(3),
    [sym__feed] = STATE(3),
    [sym__article] = STATE(3),
    [sym_header] = STATE(3),
    [sym__header_line] = STATE(4),
    [sym__header_key] = STATE(9),
    [sym_body] = STATE(3),
    [aux_sym_nvimboat_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(19),
    [sym_unread_filter] = ACTIONS(21),
    [sym_read_filter] = ACTIONS(21),
    [sym_unread_feed] = ACTIONS(24),
    [sym_read_feed] = ACTIONS(24),
    [sym_unread_article] = ACTIONS(21),
    [sym_read_article] = ACTIONS(21),
    [anon_sym_Feed] = ACTIONS(27),
    [anon_sym_Title] = ACTIONS(27),
    [anon_sym_Author] = ACTIONS(27),
    [anon_sym_Date] = ACTIONS(27),
    [anon_sym_Link] = ACTIONS(27),
    [sym_body_start] = ACTIONS(30),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(35), 2,
      sym_unread_feed,
      sym_read_feed,
    ACTIONS(33), 11,
      ts_builtin_sym_end,
      sym_unread_filter,
      sym_read_filter,
      sym_unread_article,
      sym_read_article,
      anon_sym_Feed,
      anon_sym_Title,
      anon_sym_Author,
      anon_sym_Date,
      anon_sym_Link,
      sym_body_start,
  [18] = 2,
    ACTIONS(39), 2,
      sym_unread_feed,
      sym_read_feed,
    ACTIONS(37), 11,
      ts_builtin_sym_end,
      sym_unread_filter,
      sym_read_filter,
      sym_unread_article,
      sym_read_article,
      anon_sym_Feed,
      anon_sym_Title,
      anon_sym_Author,
      anon_sym_Date,
      anon_sym_Link,
      sym_body_start,
  [36] = 2,
    ACTIONS(43), 2,
      sym_unread_feed,
      sym_read_feed,
    ACTIONS(41), 11,
      ts_builtin_sym_end,
      sym_unread_filter,
      sym_read_filter,
      sym_unread_article,
      sym_read_article,
      anon_sym_Feed,
      anon_sym_Title,
      anon_sym_Author,
      anon_sym_Date,
      anon_sym_Link,
      sym_body_start,
  [54] = 1,
    ACTIONS(45), 1,
      sym_content,
  [58] = 1,
    ACTIONS(47), 1,
      ts_builtin_sym_end,
  [62] = 1,
    ACTIONS(49), 1,
      anon_sym_COLON,
  [66] = 1,
    ACTIONS(51), 1,
      sym__expression,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 18,
  [SMALL_STATE(6)] = 36,
  [SMALL_STATE(7)] = 54,
  [SMALL_STATE(8)] = 58,
  [SMALL_STATE(9)] = 62,
  [SMALL_STATE(10)] = 66,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nvimboat, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nvimboat, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_nvimboat_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_nvimboat_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [24] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_nvimboat_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_nvimboat_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_nvimboat_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 1, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header, 1, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 2, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_body, 2, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__header_line, 3, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__header_line, 3, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [47] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_nvimboat(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "nvimboat",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
