/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 11
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 26
#define ALIAS_COUNT 0
#define TOKEN_COUNT 16
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_unread_filter = 1,
  sym_read_filter = 2,
  sym_unread_feed = 3,
  sym_read_feed = 4,
  sym_unread_article = 5,
  sym_read_article = 6,
  anon_sym_COLON = 7,
  anon_sym_Feed = 8,
  anon_sym_Title = 9,
  anon_sym_Author = 10,
  anon_sym_Date = 11,
  anon_sym_Link = 12,
  sym_body_start = 13,
  sym_content = 14,
  sym__expression = 15,
  sym_nvimboat = 16,
  sym__element = 17,
  sym__filter = 18,
  sym__feed = 19,
  sym__article = 20,
  sym_header = 21,
  sym__header_line = 22,
  sym__header_key = 23,
  sym_body = 24,
  aux_sym_nvimboat_repeat1 = 25,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_unread_filter] = "unread_filter",
  [sym_read_filter] = "read_filter",
  [sym_unread_feed] = "unread_feed",
  [sym_read_feed] = "read_feed",
  [sym_unread_article] = "unread_article",
  [sym_read_article] = "read_article",
  [anon_sym_COLON] = ":",
  [anon_sym_Feed] = "Feed",
  [anon_sym_Title] = "Title",
  [anon_sym_Author] = "Author",
  [anon_sym_Date] = "Date",
  [anon_sym_Link] = "Link",
  [sym_body_start] = "body_start",
  [sym_content] = "content",
  [sym__expression] = "_expression",
  [sym_nvimboat] = "nvimboat",
  [sym__element] = "_element",
  [sym__filter] = "_filter",
  [sym__feed] = "_feed",
  [sym__article] = "_article",
  [sym_header] = "header",
  [sym__header_line] = "_header_line",
  [sym__header_key] = "_header_key",
  [sym_body] = "body",
  [aux_sym_nvimboat_repeat1] = "nvimboat_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_unread_filter] = sym_unread_filter,
  [sym_read_filter] = sym_read_filter,
  [sym_unread_feed] = sym_unread_feed,
  [sym_read_feed] = sym_read_feed,
  [sym_unread_article] = sym_unread_article,
  [sym_read_article] = sym_read_article,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_Feed] = anon_sym_Feed,
  [anon_sym_Title] = anon_sym_Title,
  [anon_sym_Author] = anon_sym_Author,
  [anon_sym_Date] = anon_sym_Date,
  [anon_sym_Link] = anon_sym_Link,
  [sym_body_start] = sym_body_start,
  [sym_content] = sym_content,
  [sym__expression] = sym__expression,
  [sym_nvimboat] = sym_nvimboat,
  [sym__element] = sym__element,
  [sym__filter] = sym__filter,
  [sym__feed] = sym__feed,
  [sym__article] = sym__article,
  [sym_header] = sym_header,
  [sym__header_line] = sym__header_line,
  [sym__header_key] = sym__header_key,
  [sym_body] = sym_body,
  [aux_sym_nvimboat_repeat1] = aux_sym_nvimboat_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_unread_filter] = {
    .visible = true,
    .named = true,
  },
  [sym_read_filter] = {
    .visible = true,
    .named = true,
  },
  [sym_unread_feed] = {
    .visible = true,
    .named = true,
  },
  [sym_read_feed] = {
    .visible = true,
    .named = true,
  },
  [sym_unread_article] = {
    .visible = true,
    .named = true,
  },
  [sym_read_article] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Feed] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Title] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Author] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Date] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Link] = {
    .visible = true,
    .named = false,
  },
  [sym_body_start] = {
    .visible = true,
    .named = true,
  },
  [sym_content] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_nvimboat] = {
    .visible = true,
    .named = true,
  },
  [sym__element] = {
    .visible = false,
    .named = true,
  },
  [sym__filter] = {
    .visible = false,
    .named = true,
  },
  [sym__feed] = {
    .visible = false,
    .named = true,
  },
  [sym__article] = {
    .visible = false,
    .named = true,
  },
  [sym_header] = {
    .visible = true,
    .named = true,
  },
  [sym__header_line] = {
    .visible = false,
    .named = true,
  },
  [sym__header_key] = {
    .visible = false,
    .named = true,
  },
  [sym_body] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_nvimboat_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(158);
      ADVANCE_MAP(
        ' ', 5,
        ':', 255,
        '=', 80,
        'A', 143,
        'D', 87,
        'F', 104,
        'L', 115,
        'N', 6,
        'T', 117,
      );
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(262);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(1);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(263);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        ' ', 5,
        ':', 255,
        '=', 80,
        'A', 143,
        'D', 87,
        'F', 104,
        'L', 115,
        'N', 6,
        'T', 117,
      );
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(3);
      END_STATE();
    case 4:
      ADVANCE_MAP(
        ' ', 4,
        '(', 150,
        ':', 255,
        '=', 80,
        'A', 143,
        'D', 87,
        'F', 104,
        'L', 115,
        'N', 6,
        'T', 117,
        0x2502, 41,
      );
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(3);
      END_STATE();
    case 5:
      ADVANCE_MAP(
        ' ', 4,
        ':', 255,
        '=', 80,
        'A', 143,
        'D', 87,
        'F', 104,
        'L', 115,
        'N', 6,
        'T', 117,
      );
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(3);
      END_STATE();
    case 6:
      if (lookahead == ' ') ADVANCE(74);
      END_STATE();
    case 7:
      if (lookahead == ' ') ADVANCE(82);
      END_STATE();
    case 8:
      if (lookahead == ' ') ADVANCE(83);
      END_STATE();
    case 9:
      if (lookahead == ' ') ADVANCE(18);
      if (lookahead == ':') ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 10:
      if (lookahead == ' ') ADVANCE(18);
      if (lookahead == 'e') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 11:
      if (lookahead == ' ') ADVANCE(18);
      if (lookahead == 'h') ADVANCE(15);
      if (lookahead == 'q') ADVANCE(16);
      if (lookahead == 0x2502) ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 12:
      if (lookahead == ' ') ADVANCE(18);
      if (lookahead == 'p') ADVANCE(233);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 13:
      if (lookahead == ' ') ADVANCE(18);
      if (lookahead == 'r') ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 14:
      if (lookahead == ' ') ADVANCE(18);
      if (lookahead == 't') ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 15:
      if (lookahead == ' ') ADVANCE(18);
      if (lookahead == 't') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 16:
      if (lookahead == ' ') ADVANCE(18);
      if (lookahead == 'u') ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 17:
      if (lookahead == ' ') ADVANCE(18);
      if (lookahead == 'y') ADVANCE(9);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 18:
      if (lookahead == ' ') ADVANCE(18);
      if (lookahead == 0x2502) ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 19:
      if (lookahead == ' ') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 20:
      if (lookahead == ' ') ADVANCE(11);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 21:
      if (lookahead == ' ') ADVANCE(85);
      END_STATE();
    case 22:
      if (lookahead == ' ') ADVANCE(36);
      if (lookahead == ',') ADVANCE(38);
      if (lookahead == ':') ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 23:
      if (lookahead == ' ') ADVANCE(36);
      if (lookahead == ',') ADVANCE(38);
      if (lookahead == ':') ADVANCE(190);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 24:
      if (lookahead == ' ') ADVANCE(36);
      if (lookahead == ',') ADVANCE(38);
      if (lookahead == 'a') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 25:
      if (lookahead == ' ') ADVANCE(36);
      if (lookahead == ',') ADVANCE(38);
      if (lookahead == 'e') ADVANCE(29);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 26:
      if (lookahead == ' ') ADVANCE(36);
      if (lookahead == ',') ADVANCE(38);
      if (lookahead == 'g') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 27:
      if (lookahead == ' ') ADVANCE(36);
      if (lookahead == ',') ADVANCE(38);
      if (lookahead == 'h') ADVANCE(33);
      if (lookahead == 'q') ADVANCE(34);
      if (lookahead == 0x2502) ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 28:
      if (lookahead == ' ') ADVANCE(36);
      if (lookahead == ',') ADVANCE(38);
      if (lookahead == 'p') ADVANCE(250);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 29:
      if (lookahead == ' ') ADVANCE(36);
      if (lookahead == ',') ADVANCE(38);
      if (lookahead == 'r') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 30:
      if (lookahead == ' ') ADVANCE(36);
      if (lookahead == ',') ADVANCE(38);
      if (lookahead == 's') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 31:
      if (lookahead == ' ') ADVANCE(36);
      if (lookahead == ',') ADVANCE(38);
      if (lookahead == 't') ADVANCE(24);
      if (lookahead == 0x2502) ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 32:
      if (lookahead == ' ') ADVANCE(36);
      if (lookahead == ',') ADVANCE(38);
      if (lookahead == 't') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 33:
      if (lookahead == ' ') ADVANCE(36);
      if (lookahead == ',') ADVANCE(38);
      if (lookahead == 't') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 34:
      if (lookahead == ' ') ADVANCE(36);
      if (lookahead == ',') ADVANCE(38);
      if (lookahead == 'u') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 35:
      if (lookahead == ' ') ADVANCE(36);
      if (lookahead == ',') ADVANCE(38);
      if (lookahead == 'y') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 36:
      if (lookahead == ' ') ADVANCE(36);
      if (lookahead == ',') ADVANCE(38);
      if (lookahead == 0x2502) ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 37:
      if (lookahead == ' ') ADVANCE(36);
      if (lookahead == ',') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 38:
      if (lookahead == ' ') ADVANCE(31);
      if (lookahead == ',') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 39:
      if (lookahead == ' ') ADVANCE(27);
      if (lookahead == ',') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 40:
      if (lookahead == ' ') ADVANCE(81);
      END_STATE();
    case 41:
      if (lookahead == ' ') ADVANCE(153);
      END_STATE();
    case 42:
      if (lookahead == ' ') ADVANCE(84);
      END_STATE();
    case 43:
      if (lookahead == ' ') ADVANCE(48);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(56);
      END_STATE();
    case 44:
      if (lookahead == ' ') ADVANCE(62);
      if (lookahead == ',') ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(72);
      END_STATE();
    case 45:
      if (lookahead == ' ') ADVANCE(155);
      END_STATE();
    case 46:
      if (lookahead == ' ') ADVANCE(55);
      if (lookahead == ':') ADVANCE(72);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(56);
      END_STATE();
    case 47:
      if (lookahead == ' ') ADVANCE(55);
      if (lookahead == 'e') ADVANCE(50);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(56);
      END_STATE();
    case 48:
      if (lookahead == ' ') ADVANCE(55);
      if (lookahead == 'h') ADVANCE(52);
      if (lookahead == 'q') ADVANCE(53);
      if (lookahead == 0x2502) ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(56);
      END_STATE();
    case 49:
      if (lookahead == ' ') ADVANCE(55);
      if (lookahead == 'p') ADVANCE(203);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(56);
      END_STATE();
    case 50:
      if (lookahead == ' ') ADVANCE(55);
      if (lookahead == 'r') ADVANCE(54);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(56);
      END_STATE();
    case 51:
      if (lookahead == ' ') ADVANCE(55);
      if (lookahead == 't') ADVANCE(49);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(56);
      END_STATE();
    case 52:
      if (lookahead == ' ') ADVANCE(55);
      if (lookahead == 't') ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(56);
      END_STATE();
    case 53:
      if (lookahead == ' ') ADVANCE(55);
      if (lookahead == 'u') ADVANCE(47);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(56);
      END_STATE();
    case 54:
      if (lookahead == ' ') ADVANCE(55);
      if (lookahead == 'y') ADVANCE(46);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(56);
      END_STATE();
    case 55:
      if (lookahead == ' ') ADVANCE(55);
      if (lookahead == 0x2502) ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(56);
      END_STATE();
    case 56:
      if (lookahead == ' ') ADVANCE(55);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(56);
      END_STATE();
    case 57:
      if (lookahead == ' ') ADVANCE(71);
      if (lookahead == ',') ADVANCE(73);
      if (lookahead == ':') ADVANCE(173);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(72);
      END_STATE();
    case 58:
      if (lookahead == ' ') ADVANCE(71);
      if (lookahead == ',') ADVANCE(73);
      if (lookahead == ':') ADVANCE(72);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(72);
      END_STATE();
    case 59:
      if (lookahead == ' ') ADVANCE(71);
      if (lookahead == ',') ADVANCE(73);
      if (lookahead == 'a') ADVANCE(61);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(72);
      END_STATE();
    case 60:
      if (lookahead == ' ') ADVANCE(71);
      if (lookahead == ',') ADVANCE(73);
      if (lookahead == 'e') ADVANCE(64);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(72);
      END_STATE();
    case 61:
      if (lookahead == ' ') ADVANCE(71);
      if (lookahead == ',') ADVANCE(73);
      if (lookahead == 'g') ADVANCE(65);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(72);
      END_STATE();
    case 62:
      if (lookahead == ' ') ADVANCE(71);
      if (lookahead == ',') ADVANCE(73);
      if (lookahead == 'h') ADVANCE(67);
      if (lookahead == 'q') ADVANCE(69);
      if (lookahead == 0x2502) ADVANCE(44);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(72);
      END_STATE();
    case 63:
      if (lookahead == ' ') ADVANCE(71);
      if (lookahead == ',') ADVANCE(73);
      if (lookahead == 'p') ADVANCE(220);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(72);
      END_STATE();
    case 64:
      if (lookahead == ' ') ADVANCE(71);
      if (lookahead == ',') ADVANCE(73);
      if (lookahead == 'r') ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(72);
      END_STATE();
    case 65:
      if (lookahead == ' ') ADVANCE(71);
      if (lookahead == ',') ADVANCE(73);
      if (lookahead == 's') ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(72);
      END_STATE();
    case 66:
      if (lookahead == ' ') ADVANCE(71);
      if (lookahead == ',') ADVANCE(73);
      if (lookahead == 't') ADVANCE(63);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(72);
      END_STATE();
    case 67:
      if (lookahead == ' ') ADVANCE(71);
      if (lookahead == ',') ADVANCE(73);
      if (lookahead == 't') ADVANCE(66);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(72);
      END_STATE();
    case 68:
      if (lookahead == ' ') ADVANCE(71);
      if (lookahead == ',') ADVANCE(73);
      if (lookahead == 't') ADVANCE(59);
      if (lookahead == 0x2502) ADVANCE(44);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(72);
      END_STATE();
    case 69:
      if (lookahead == ' ') ADVANCE(71);
      if (lookahead == ',') ADVANCE(73);
      if (lookahead == 'u') ADVANCE(60);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(72);
      END_STATE();
    case 70:
      if (lookahead == ' ') ADVANCE(71);
      if (lookahead == ',') ADVANCE(73);
      if (lookahead == 'y') ADVANCE(58);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(72);
      END_STATE();
    case 71:
      if (lookahead == ' ') ADVANCE(71);
      if (lookahead == ',') ADVANCE(73);
      if (lookahead == 0x2502) ADVANCE(44);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(72);
      END_STATE();
    case 72:
      if (lookahead == ' ') ADVANCE(71);
      if (lookahead == ',') ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(72);
      END_STATE();
    case 73:
      if (lookahead == ' ') ADVANCE(68);
      if (lookahead == ',') ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(72);
      END_STATE();
    case 74:
      if (lookahead == '(') ADVANCE(157);
      if (lookahead == 0x2502) ADVANCE(45);
      END_STATE();
    case 75:
      if (lookahead == ')') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(75);
      END_STATE();
    case 76:
      if (lookahead == ')') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(76);
      END_STATE();
    case 77:
      if (lookahead == '/') ADVANCE(151);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(77);
      END_STATE();
    case 78:
      if (lookahead == '/') ADVANCE(156);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(78);
      END_STATE();
    case 79:
      if (lookahead == '=') ADVANCE(261);
      END_STATE();
    case 80:
      if (lookahead == '=') ADVANCE(7);
      END_STATE();
    case 81:
      if (lookahead == '=') ADVANCE(79);
      END_STATE();
    case 82:
      if (lookahead == 'A') ADVANCE(136);
      END_STATE();
    case 83:
      ADVANCE_MAP(
        'A', 131,
        'D', 107,
        'F', 102,
        'J', 88,
        'M', 86,
        'N', 126,
        'O', 95,
        'S', 103,
      );
      END_STATE();
    case 84:
      ADVANCE_MAP(
        'A', 132,
        'D', 109,
        'F', 105,
        'J', 90,
        'M', 89,
        'N', 128,
        'O', 96,
        'S', 106,
      );
      END_STATE();
    case 85:
      if (lookahead == 'B') ADVANCE(108);
      END_STATE();
    case 86:
      if (lookahead == 'a') ADVANCE(148);
      END_STATE();
    case 87:
      if (lookahead == 'a') ADVANCE(141);
      END_STATE();
    case 88:
      if (lookahead == 'a') ADVANCE(123);
      if (lookahead == 'u') ADVANCE(146);
      END_STATE();
    case 89:
      if (lookahead == 'a') ADVANCE(149);
      END_STATE();
    case 90:
      if (lookahead == 'a') ADVANCE(124);
      if (lookahead == 'u') ADVANCE(147);
      END_STATE();
    case 91:
      if (lookahead == 'b') ADVANCE(254);
      END_STATE();
    case 92:
      if (lookahead == 'b') ADVANCE(253);
      END_STATE();
    case 93:
      if (lookahead == 'c') ADVANCE(254);
      END_STATE();
    case 94:
      if (lookahead == 'c') ADVANCE(253);
      END_STATE();
    case 95:
      if (lookahead == 'c') ADVANCE(139);
      END_STATE();
    case 96:
      if (lookahead == 'c') ADVANCE(140);
      END_STATE();
    case 97:
      if (lookahead == 'c') ADVANCE(121);
      END_STATE();
    case 98:
      if (lookahead == 'd') ADVANCE(256);
      END_STATE();
    case 99:
      if (lookahead == 'e') ADVANCE(98);
      END_STATE();
    case 100:
      if (lookahead == 'e') ADVANCE(259);
      END_STATE();
    case 101:
      if (lookahead == 'e') ADVANCE(257);
      END_STATE();
    case 102:
      if (lookahead == 'e') ADVANCE(91);
      END_STATE();
    case 103:
      if (lookahead == 'e') ADVANCE(129);
      END_STATE();
    case 104:
      if (lookahead == 'e') ADVANCE(99);
      END_STATE();
    case 105:
      if (lookahead == 'e') ADVANCE(92);
      END_STATE();
    case 106:
      if (lookahead == 'e') ADVANCE(130);
      END_STATE();
    case 107:
      if (lookahead == 'e') ADVANCE(93);
      END_STATE();
    case 108:
      if (lookahead == 'e') ADVANCE(113);
      END_STATE();
    case 109:
      if (lookahead == 'e') ADVANCE(94);
      END_STATE();
    case 110:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 111:
      if (lookahead == 'g') ADVANCE(254);
      END_STATE();
    case 112:
      if (lookahead == 'g') ADVANCE(253);
      END_STATE();
    case 113:
      if (lookahead == 'g') ADVANCE(118);
      END_STATE();
    case 114:
      if (lookahead == 'h') ADVANCE(127);
      END_STATE();
    case 115:
      if (lookahead == 'i') ADVANCE(122);
      END_STATE();
    case 116:
      if (lookahead == 'i') ADVANCE(97);
      END_STATE();
    case 117:
      if (lookahead == 'i') ADVANCE(138);
      END_STATE();
    case 118:
      if (lookahead == 'i') ADVANCE(125);
      END_STATE();
    case 119:
      if (lookahead == 'k') ADVANCE(260);
      END_STATE();
    case 120:
      if (lookahead == 'l') ADVANCE(101);
      END_STATE();
    case 121:
      if (lookahead == 'l') ADVANCE(110);
      END_STATE();
    case 122:
      if (lookahead == 'n') ADVANCE(119);
      END_STATE();
    case 123:
      if (lookahead == 'n') ADVANCE(254);
      END_STATE();
    case 124:
      if (lookahead == 'n') ADVANCE(253);
      END_STATE();
    case 125:
      if (lookahead == 'n') ADVANCE(40);
      END_STATE();
    case 126:
      if (lookahead == 'o') ADVANCE(144);
      END_STATE();
    case 127:
      if (lookahead == 'o') ADVANCE(133);
      END_STATE();
    case 128:
      if (lookahead == 'o') ADVANCE(145);
      END_STATE();
    case 129:
      if (lookahead == 'p') ADVANCE(254);
      END_STATE();
    case 130:
      if (lookahead == 'p') ADVANCE(253);
      END_STATE();
    case 131:
      if (lookahead == 'p') ADVANCE(134);
      if (lookahead == 'u') ADVANCE(111);
      END_STATE();
    case 132:
      if (lookahead == 'p') ADVANCE(135);
      if (lookahead == 'u') ADVANCE(112);
      END_STATE();
    case 133:
      if (lookahead == 'r') ADVANCE(258);
      END_STATE();
    case 134:
      if (lookahead == 'r') ADVANCE(254);
      END_STATE();
    case 135:
      if (lookahead == 'r') ADVANCE(253);
      END_STATE();
    case 136:
      if (lookahead == 'r') ADVANCE(142);
      END_STATE();
    case 137:
      if (lookahead == 't') ADVANCE(114);
      END_STATE();
    case 138:
      if (lookahead == 't') ADVANCE(120);
      END_STATE();
    case 139:
      if (lookahead == 't') ADVANCE(254);
      END_STATE();
    case 140:
      if (lookahead == 't') ADVANCE(253);
      END_STATE();
    case 141:
      if (lookahead == 't') ADVANCE(100);
      END_STATE();
    case 142:
      if (lookahead == 't') ADVANCE(116);
      END_STATE();
    case 143:
      if (lookahead == 'u') ADVANCE(137);
      END_STATE();
    case 144:
      if (lookahead == 'v') ADVANCE(254);
      END_STATE();
    case 145:
      if (lookahead == 'v') ADVANCE(253);
      END_STATE();
    case 146:
      if (lookahead == 'l' ||
          lookahead == 'n') ADVANCE(254);
      END_STATE();
    case 147:
      if (lookahead == 'l' ||
          lookahead == 'n') ADVANCE(253);
      END_STATE();
    case 148:
      if (lookahead == 'r' ||
          lookahead == 'y') ADVANCE(254);
      END_STATE();
    case 149:
      if (lookahead == 'r' ||
          lookahead == 'y') ADVANCE(253);
      END_STATE();
    case 150:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(77);
      END_STATE();
    case 151:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(75);
      END_STATE();
    case 152:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      END_STATE();
    case 153:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(152);
      END_STATE();
    case 154:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 155:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(154);
      END_STATE();
    case 156:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(76);
      END_STATE();
    case 157:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(78);
      END_STATE();
    case 158:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 159:
      ACCEPT_TOKEN(sym_unread_filter);
      if (lookahead == ' ') ADVANCE(172);
      if (lookahead == ',') ADVANCE(174);
      if (lookahead == ':') ADVANCE(173);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(173);
      END_STATE();
    case 160:
      ACCEPT_TOKEN(sym_unread_filter);
      if (lookahead == ' ') ADVANCE(172);
      if (lookahead == ',') ADVANCE(174);
      if (lookahead == 'a') ADVANCE(162);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(173);
      END_STATE();
    case 161:
      ACCEPT_TOKEN(sym_unread_filter);
      if (lookahead == ' ') ADVANCE(172);
      if (lookahead == ',') ADVANCE(174);
      if (lookahead == 'e') ADVANCE(165);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(173);
      END_STATE();
    case 162:
      ACCEPT_TOKEN(sym_unread_filter);
      if (lookahead == ' ') ADVANCE(172);
      if (lookahead == ',') ADVANCE(174);
      if (lookahead == 'g') ADVANCE(166);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(173);
      END_STATE();
    case 163:
      ACCEPT_TOKEN(sym_unread_filter);
      if (lookahead == ' ') ADVANCE(172);
      if (lookahead == ',') ADVANCE(174);
      if (lookahead == 'h') ADVANCE(169);
      if (lookahead == 'q') ADVANCE(170);
      if (lookahead == 0x2502) ADVANCE(175);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(173);
      END_STATE();
    case 164:
      ACCEPT_TOKEN(sym_unread_filter);
      if (lookahead == ' ') ADVANCE(172);
      if (lookahead == ',') ADVANCE(174);
      if (lookahead == 'p') ADVANCE(173);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(173);
      END_STATE();
    case 165:
      ACCEPT_TOKEN(sym_unread_filter);
      if (lookahead == ' ') ADVANCE(172);
      if (lookahead == ',') ADVANCE(174);
      if (lookahead == 'r') ADVANCE(171);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(173);
      END_STATE();
    case 166:
      ACCEPT_TOKEN(sym_unread_filter);
      if (lookahead == ' ') ADVANCE(172);
      if (lookahead == ',') ADVANCE(174);
      if (lookahead == 's') ADVANCE(159);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(173);
      END_STATE();
    case 167:
      ACCEPT_TOKEN(sym_unread_filter);
      if (lookahead == ' ') ADVANCE(172);
      if (lookahead == ',') ADVANCE(174);
      if (lookahead == 't') ADVANCE(160);
      if (lookahead == 0x2502) ADVANCE(175);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(173);
      END_STATE();
    case 168:
      ACCEPT_TOKEN(sym_unread_filter);
      if (lookahead == ' ') ADVANCE(172);
      if (lookahead == ',') ADVANCE(174);
      if (lookahead == 't') ADVANCE(164);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(173);
      END_STATE();
    case 169:
      ACCEPT_TOKEN(sym_unread_filter);
      if (lookahead == ' ') ADVANCE(172);
      if (lookahead == ',') ADVANCE(174);
      if (lookahead == 't') ADVANCE(168);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(173);
      END_STATE();
    case 170:
      ACCEPT_TOKEN(sym_unread_filter);
      if (lookahead == ' ') ADVANCE(172);
      if (lookahead == ',') ADVANCE(174);
      if (lookahead == 'u') ADVANCE(161);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(173);
      END_STATE();
    case 171:
      ACCEPT_TOKEN(sym_unread_filter);
      if (lookahead == ' ') ADVANCE(172);
      if (lookahead == ',') ADVANCE(174);
      if (lookahead == 'y') ADVANCE(159);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(173);
      END_STATE();
    case 172:
      ACCEPT_TOKEN(sym_unread_filter);
      if (lookahead == ' ') ADVANCE(172);
      if (lookahead == ',') ADVANCE(174);
      if (lookahead == 0x2502) ADVANCE(175);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(173);
      END_STATE();
    case 173:
      ACCEPT_TOKEN(sym_unread_filter);
      if (lookahead == ' ') ADVANCE(172);
      if (lookahead == ',') ADVANCE(174);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(173);
      END_STATE();
    case 174:
      ACCEPT_TOKEN(sym_unread_filter);
      if (lookahead == ' ') ADVANCE(167);
      if (lookahead == ',') ADVANCE(174);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(173);
      END_STATE();
    case 175:
      ACCEPT_TOKEN(sym_unread_filter);
      if (lookahead == ' ') ADVANCE(163);
      if (lookahead == ',') ADVANCE(174);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(173);
      END_STATE();
    case 176:
      ACCEPT_TOKEN(sym_read_filter);
      if (lookahead == ' ') ADVANCE(189);
      if (lookahead == ',') ADVANCE(191);
      if (lookahead == ':') ADVANCE(190);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(190);
      END_STATE();
    case 177:
      ACCEPT_TOKEN(sym_read_filter);
      if (lookahead == ' ') ADVANCE(189);
      if (lookahead == ',') ADVANCE(191);
      if (lookahead == 'a') ADVANCE(179);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(190);
      END_STATE();
    case 178:
      ACCEPT_TOKEN(sym_read_filter);
      if (lookahead == ' ') ADVANCE(189);
      if (lookahead == ',') ADVANCE(191);
      if (lookahead == 'e') ADVANCE(182);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(190);
      END_STATE();
    case 179:
      ACCEPT_TOKEN(sym_read_filter);
      if (lookahead == ' ') ADVANCE(189);
      if (lookahead == ',') ADVANCE(191);
      if (lookahead == 'g') ADVANCE(183);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(190);
      END_STATE();
    case 180:
      ACCEPT_TOKEN(sym_read_filter);
      if (lookahead == ' ') ADVANCE(189);
      if (lookahead == ',') ADVANCE(191);
      if (lookahead == 'h') ADVANCE(186);
      if (lookahead == 'q') ADVANCE(187);
      if (lookahead == 0x2502) ADVANCE(192);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(190);
      END_STATE();
    case 181:
      ACCEPT_TOKEN(sym_read_filter);
      if (lookahead == ' ') ADVANCE(189);
      if (lookahead == ',') ADVANCE(191);
      if (lookahead == 'p') ADVANCE(190);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(190);
      END_STATE();
    case 182:
      ACCEPT_TOKEN(sym_read_filter);
      if (lookahead == ' ') ADVANCE(189);
      if (lookahead == ',') ADVANCE(191);
      if (lookahead == 'r') ADVANCE(188);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(190);
      END_STATE();
    case 183:
      ACCEPT_TOKEN(sym_read_filter);
      if (lookahead == ' ') ADVANCE(189);
      if (lookahead == ',') ADVANCE(191);
      if (lookahead == 's') ADVANCE(176);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(190);
      END_STATE();
    case 184:
      ACCEPT_TOKEN(sym_read_filter);
      if (lookahead == ' ') ADVANCE(189);
      if (lookahead == ',') ADVANCE(191);
      if (lookahead == 't') ADVANCE(177);
      if (lookahead == 0x2502) ADVANCE(192);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(190);
      END_STATE();
    case 185:
      ACCEPT_TOKEN(sym_read_filter);
      if (lookahead == ' ') ADVANCE(189);
      if (lookahead == ',') ADVANCE(191);
      if (lookahead == 't') ADVANCE(181);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(190);
      END_STATE();
    case 186:
      ACCEPT_TOKEN(sym_read_filter);
      if (lookahead == ' ') ADVANCE(189);
      if (lookahead == ',') ADVANCE(191);
      if (lookahead == 't') ADVANCE(185);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(190);
      END_STATE();
    case 187:
      ACCEPT_TOKEN(sym_read_filter);
      if (lookahead == ' ') ADVANCE(189);
      if (lookahead == ',') ADVANCE(191);
      if (lookahead == 'u') ADVANCE(178);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(190);
      END_STATE();
    case 188:
      ACCEPT_TOKEN(sym_read_filter);
      if (lookahead == ' ') ADVANCE(189);
      if (lookahead == ',') ADVANCE(191);
      if (lookahead == 'y') ADVANCE(176);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(190);
      END_STATE();
    case 189:
      ACCEPT_TOKEN(sym_read_filter);
      if (lookahead == ' ') ADVANCE(189);
      if (lookahead == ',') ADVANCE(191);
      if (lookahead == 0x2502) ADVANCE(192);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(190);
      END_STATE();
    case 190:
      ACCEPT_TOKEN(sym_read_filter);
      if (lookahead == ' ') ADVANCE(189);
      if (lookahead == ',') ADVANCE(191);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(190);
      END_STATE();
    case 191:
      ACCEPT_TOKEN(sym_read_filter);
      if (lookahead == ' ') ADVANCE(184);
      if (lookahead == ',') ADVANCE(191);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(190);
      END_STATE();
    case 192:
      ACCEPT_TOKEN(sym_read_filter);
      if (lookahead == ' ') ADVANCE(180);
      if (lookahead == ',') ADVANCE(191);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(190);
      END_STATE();
    case 193:
      ACCEPT_TOKEN(sym_unread_feed);
      if (lookahead == ' ') ADVANCE(202);
      if (lookahead == ':') ADVANCE(220);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(203);
      END_STATE();
    case 194:
      ACCEPT_TOKEN(sym_unread_feed);
      if (lookahead == ' ') ADVANCE(202);
      if (lookahead == 'e') ADVANCE(197);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(203);
      END_STATE();
    case 195:
      ACCEPT_TOKEN(sym_unread_feed);
      if (lookahead == ' ') ADVANCE(202);
      if (lookahead == 'h') ADVANCE(199);
      if (lookahead == 'q') ADVANCE(200);
      if (lookahead == 0x2502) ADVANCE(204);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(203);
      END_STATE();
    case 196:
      ACCEPT_TOKEN(sym_unread_feed);
      if (lookahead == ' ') ADVANCE(202);
      if (lookahead == 'p') ADVANCE(203);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(203);
      END_STATE();
    case 197:
      ACCEPT_TOKEN(sym_unread_feed);
      if (lookahead == ' ') ADVANCE(202);
      if (lookahead == 'r') ADVANCE(201);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(203);
      END_STATE();
    case 198:
      ACCEPT_TOKEN(sym_unread_feed);
      if (lookahead == ' ') ADVANCE(202);
      if (lookahead == 't') ADVANCE(196);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(203);
      END_STATE();
    case 199:
      ACCEPT_TOKEN(sym_unread_feed);
      if (lookahead == ' ') ADVANCE(202);
      if (lookahead == 't') ADVANCE(198);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(203);
      END_STATE();
    case 200:
      ACCEPT_TOKEN(sym_unread_feed);
      if (lookahead == ' ') ADVANCE(202);
      if (lookahead == 'u') ADVANCE(194);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(203);
      END_STATE();
    case 201:
      ACCEPT_TOKEN(sym_unread_feed);
      if (lookahead == ' ') ADVANCE(202);
      if (lookahead == 'y') ADVANCE(193);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(203);
      END_STATE();
    case 202:
      ACCEPT_TOKEN(sym_unread_feed);
      if (lookahead == ' ') ADVANCE(202);
      if (lookahead == 0x2502) ADVANCE(204);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(203);
      END_STATE();
    case 203:
      ACCEPT_TOKEN(sym_unread_feed);
      if (lookahead == ' ') ADVANCE(202);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(203);
      END_STATE();
    case 204:
      ACCEPT_TOKEN(sym_unread_feed);
      if (lookahead == ' ') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(203);
      END_STATE();
    case 205:
      ACCEPT_TOKEN(sym_unread_feed);
      if (lookahead == ' ') ADVANCE(219);
      if (lookahead == ',') ADVANCE(221);
      if (lookahead == ':') ADVANCE(220);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(220);
      END_STATE();
    case 206:
      ACCEPT_TOKEN(sym_unread_feed);
      if (lookahead == ' ') ADVANCE(219);
      if (lookahead == ',') ADVANCE(221);
      if (lookahead == ':') ADVANCE(173);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(220);
      END_STATE();
    case 207:
      ACCEPT_TOKEN(sym_unread_feed);
      if (lookahead == ' ') ADVANCE(219);
      if (lookahead == ',') ADVANCE(221);
      if (lookahead == 'a') ADVANCE(209);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(220);
      END_STATE();
    case 208:
      ACCEPT_TOKEN(sym_unread_feed);
      if (lookahead == ' ') ADVANCE(219);
      if (lookahead == ',') ADVANCE(221);
      if (lookahead == 'e') ADVANCE(212);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(220);
      END_STATE();
    case 209:
      ACCEPT_TOKEN(sym_unread_feed);
      if (lookahead == ' ') ADVANCE(219);
      if (lookahead == ',') ADVANCE(221);
      if (lookahead == 'g') ADVANCE(213);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(220);
      END_STATE();
    case 210:
      ACCEPT_TOKEN(sym_unread_feed);
      if (lookahead == ' ') ADVANCE(219);
      if (lookahead == ',') ADVANCE(221);
      if (lookahead == 'h') ADVANCE(216);
      if (lookahead == 'q') ADVANCE(217);
      if (lookahead == 0x2502) ADVANCE(222);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(220);
      END_STATE();
    case 211:
      ACCEPT_TOKEN(sym_unread_feed);
      if (lookahead == ' ') ADVANCE(219);
      if (lookahead == ',') ADVANCE(221);
      if (lookahead == 'p') ADVANCE(220);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(220);
      END_STATE();
    case 212:
      ACCEPT_TOKEN(sym_unread_feed);
      if (lookahead == ' ') ADVANCE(219);
      if (lookahead == ',') ADVANCE(221);
      if (lookahead == 'r') ADVANCE(218);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(220);
      END_STATE();
    case 213:
      ACCEPT_TOKEN(sym_unread_feed);
      if (lookahead == ' ') ADVANCE(219);
      if (lookahead == ',') ADVANCE(221);
      if (lookahead == 's') ADVANCE(206);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(220);
      END_STATE();
    case 214:
      ACCEPT_TOKEN(sym_unread_feed);
      if (lookahead == ' ') ADVANCE(219);
      if (lookahead == ',') ADVANCE(221);
      if (lookahead == 't') ADVANCE(207);
      if (lookahead == 0x2502) ADVANCE(222);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(220);
      END_STATE();
    case 215:
      ACCEPT_TOKEN(sym_unread_feed);
      if (lookahead == ' ') ADVANCE(219);
      if (lookahead == ',') ADVANCE(221);
      if (lookahead == 't') ADVANCE(211);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(220);
      END_STATE();
    case 216:
      ACCEPT_TOKEN(sym_unread_feed);
      if (lookahead == ' ') ADVANCE(219);
      if (lookahead == ',') ADVANCE(221);
      if (lookahead == 't') ADVANCE(215);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(220);
      END_STATE();
    case 217:
      ACCEPT_TOKEN(sym_unread_feed);
      if (lookahead == ' ') ADVANCE(219);
      if (lookahead == ',') ADVANCE(221);
      if (lookahead == 'u') ADVANCE(208);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(220);
      END_STATE();
    case 218:
      ACCEPT_TOKEN(sym_unread_feed);
      if (lookahead == ' ') ADVANCE(219);
      if (lookahead == ',') ADVANCE(221);
      if (lookahead == 'y') ADVANCE(205);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(220);
      END_STATE();
    case 219:
      ACCEPT_TOKEN(sym_unread_feed);
      if (lookahead == ' ') ADVANCE(219);
      if (lookahead == ',') ADVANCE(221);
      if (lookahead == 0x2502) ADVANCE(222);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(220);
      END_STATE();
    case 220:
      ACCEPT_TOKEN(sym_unread_feed);
      if (lookahead == ' ') ADVANCE(219);
      if (lookahead == ',') ADVANCE(221);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(220);
      END_STATE();
    case 221:
      ACCEPT_TOKEN(sym_unread_feed);
      if (lookahead == ' ') ADVANCE(214);
      if (lookahead == ',') ADVANCE(221);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(220);
      END_STATE();
    case 222:
      ACCEPT_TOKEN(sym_unread_feed);
      if (lookahead == ' ') ADVANCE(210);
      if (lookahead == ',') ADVANCE(221);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(220);
      END_STATE();
    case 223:
      ACCEPT_TOKEN(sym_read_feed);
      if (lookahead == ' ') ADVANCE(232);
      if (lookahead == ':') ADVANCE(250);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(233);
      END_STATE();
    case 224:
      ACCEPT_TOKEN(sym_read_feed);
      if (lookahead == ' ') ADVANCE(232);
      if (lookahead == 'e') ADVANCE(227);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(233);
      END_STATE();
    case 225:
      ACCEPT_TOKEN(sym_read_feed);
      if (lookahead == ' ') ADVANCE(232);
      if (lookahead == 'h') ADVANCE(229);
      if (lookahead == 'q') ADVANCE(230);
      if (lookahead == 0x2502) ADVANCE(234);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(233);
      END_STATE();
    case 226:
      ACCEPT_TOKEN(sym_read_feed);
      if (lookahead == ' ') ADVANCE(232);
      if (lookahead == 'p') ADVANCE(233);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(233);
      END_STATE();
    case 227:
      ACCEPT_TOKEN(sym_read_feed);
      if (lookahead == ' ') ADVANCE(232);
      if (lookahead == 'r') ADVANCE(231);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(233);
      END_STATE();
    case 228:
      ACCEPT_TOKEN(sym_read_feed);
      if (lookahead == ' ') ADVANCE(232);
      if (lookahead == 't') ADVANCE(226);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(233);
      END_STATE();
    case 229:
      ACCEPT_TOKEN(sym_read_feed);
      if (lookahead == ' ') ADVANCE(232);
      if (lookahead == 't') ADVANCE(228);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(233);
      END_STATE();
    case 230:
      ACCEPT_TOKEN(sym_read_feed);
      if (lookahead == ' ') ADVANCE(232);
      if (lookahead == 'u') ADVANCE(224);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(233);
      END_STATE();
    case 231:
      ACCEPT_TOKEN(sym_read_feed);
      if (lookahead == ' ') ADVANCE(232);
      if (lookahead == 'y') ADVANCE(223);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(233);
      END_STATE();
    case 232:
      ACCEPT_TOKEN(sym_read_feed);
      if (lookahead == ' ') ADVANCE(232);
      if (lookahead == 0x2502) ADVANCE(234);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(233);
      END_STATE();
    case 233:
      ACCEPT_TOKEN(sym_read_feed);
      if (lookahead == ' ') ADVANCE(232);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(233);
      END_STATE();
    case 234:
      ACCEPT_TOKEN(sym_read_feed);
      if (lookahead == ' ') ADVANCE(225);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(233);
      END_STATE();
    case 235:
      ACCEPT_TOKEN(sym_read_feed);
      if (lookahead == ' ') ADVANCE(249);
      if (lookahead == ',') ADVANCE(251);
      if (lookahead == ':') ADVANCE(250);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(250);
      END_STATE();
    case 236:
      ACCEPT_TOKEN(sym_read_feed);
      if (lookahead == ' ') ADVANCE(249);
      if (lookahead == ',') ADVANCE(251);
      if (lookahead == ':') ADVANCE(190);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(250);
      END_STATE();
    case 237:
      ACCEPT_TOKEN(sym_read_feed);
      if (lookahead == ' ') ADVANCE(249);
      if (lookahead == ',') ADVANCE(251);
      if (lookahead == 'a') ADVANCE(239);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(250);
      END_STATE();
    case 238:
      ACCEPT_TOKEN(sym_read_feed);
      if (lookahead == ' ') ADVANCE(249);
      if (lookahead == ',') ADVANCE(251);
      if (lookahead == 'e') ADVANCE(242);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(250);
      END_STATE();
    case 239:
      ACCEPT_TOKEN(sym_read_feed);
      if (lookahead == ' ') ADVANCE(249);
      if (lookahead == ',') ADVANCE(251);
      if (lookahead == 'g') ADVANCE(243);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(250);
      END_STATE();
    case 240:
      ACCEPT_TOKEN(sym_read_feed);
      if (lookahead == ' ') ADVANCE(249);
      if (lookahead == ',') ADVANCE(251);
      if (lookahead == 'h') ADVANCE(246);
      if (lookahead == 'q') ADVANCE(247);
      if (lookahead == 0x2502) ADVANCE(252);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(250);
      END_STATE();
    case 241:
      ACCEPT_TOKEN(sym_read_feed);
      if (lookahead == ' ') ADVANCE(249);
      if (lookahead == ',') ADVANCE(251);
      if (lookahead == 'p') ADVANCE(250);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(250);
      END_STATE();
    case 242:
      ACCEPT_TOKEN(sym_read_feed);
      if (lookahead == ' ') ADVANCE(249);
      if (lookahead == ',') ADVANCE(251);
      if (lookahead == 'r') ADVANCE(248);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(250);
      END_STATE();
    case 243:
      ACCEPT_TOKEN(sym_read_feed);
      if (lookahead == ' ') ADVANCE(249);
      if (lookahead == ',') ADVANCE(251);
      if (lookahead == 's') ADVANCE(236);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(250);
      END_STATE();
    case 244:
      ACCEPT_TOKEN(sym_read_feed);
      if (lookahead == ' ') ADVANCE(249);
      if (lookahead == ',') ADVANCE(251);
      if (lookahead == 't') ADVANCE(237);
      if (lookahead == 0x2502) ADVANCE(252);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(250);
      END_STATE();
    case 245:
      ACCEPT_TOKEN(sym_read_feed);
      if (lookahead == ' ') ADVANCE(249);
      if (lookahead == ',') ADVANCE(251);
      if (lookahead == 't') ADVANCE(241);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(250);
      END_STATE();
    case 246:
      ACCEPT_TOKEN(sym_read_feed);
      if (lookahead == ' ') ADVANCE(249);
      if (lookahead == ',') ADVANCE(251);
      if (lookahead == 't') ADVANCE(245);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(250);
      END_STATE();
    case 247:
      ACCEPT_TOKEN(sym_read_feed);
      if (lookahead == ' ') ADVANCE(249);
      if (lookahead == ',') ADVANCE(251);
      if (lookahead == 'u') ADVANCE(238);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(250);
      END_STATE();
    case 248:
      ACCEPT_TOKEN(sym_read_feed);
      if (lookahead == ' ') ADVANCE(249);
      if (lookahead == ',') ADVANCE(251);
      if (lookahead == 'y') ADVANCE(235);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(250);
      END_STATE();
    case 249:
      ACCEPT_TOKEN(sym_read_feed);
      if (lookahead == ' ') ADVANCE(249);
      if (lookahead == ',') ADVANCE(251);
      if (lookahead == 0x2502) ADVANCE(252);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(250);
      END_STATE();
    case 250:
      ACCEPT_TOKEN(sym_read_feed);
      if (lookahead == ' ') ADVANCE(249);
      if (lookahead == ',') ADVANCE(251);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(250);
      END_STATE();
    case 251:
      ACCEPT_TOKEN(sym_read_feed);
      if (lookahead == ' ') ADVANCE(244);
      if (lookahead == ',') ADVANCE(251);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(250);
      END_STATE();
    case 252:
      ACCEPT_TOKEN(sym_read_feed);
      if (lookahead == ' ') ADVANCE(240);
      if (lookahead == ',') ADVANCE(251);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(250);
      END_STATE();
    case 253:
      ACCEPT_TOKEN(sym_unread_article);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(253);
      END_STATE();
    case 254:
      ACCEPT_TOKEN(sym_read_article);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(254);
      END_STATE();
    case 255:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 256:
      ACCEPT_TOKEN(anon_sym_Feed);
      END_STATE();
    case 257:
      ACCEPT_TOKEN(anon_sym_Title);
      END_STATE();
    case 258:
      ACCEPT_TOKEN(anon_sym_Author);
      END_STATE();
    case 259:
      ACCEPT_TOKEN(anon_sym_Date);
      END_STATE();
    case 260:
      ACCEPT_TOKEN(anon_sym_Link);
      END_STATE();
    case 261:
      ACCEPT_TOKEN(sym_body_start);
      END_STATE();
    case 262:
      ACCEPT_TOKEN(sym_content);
      if (lookahead == '\n') ADVANCE(262);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(1);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 263:
      ACCEPT_TOKEN(sym_content);
      if (lookahead == '\n') ADVANCE(263);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 264:
      ACCEPT_TOKEN(sym__expression);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(264);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(265);
      END_STATE();
    case 265:
      ACCEPT_TOKEN(sym__expression);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(265);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 264},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_unread_filter] = ACTIONS(1),
    [sym_read_filter] = ACTIONS(1),
    [sym_unread_feed] = ACTIONS(1),
    [sym_read_feed] = ACTIONS(1),
    [sym_unread_article] = ACTIONS(1),
    [sym_read_article] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_Feed] = ACTIONS(1),
    [anon_sym_Title] = ACTIONS(1),
    [anon_sym_Author] = ACTIONS(1),
    [anon_sym_Date] = ACTIONS(1),
    [anon_sym_Link] = ACTIONS(1),
    [sym_body_start] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_nvimboat] = STATE(8),
    [sym__element] = STATE(2),
    [sym__filter] = STATE(2),
    [sym__feed] = STATE(2),
    [sym__article] = STATE(2),
    [sym_header] = STATE(2),
    [sym__header_line] = STATE(4),
    [sym__header_key] = STATE(9),
    [sym_body] = STATE(2),
    [aux_sym_nvimboat_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_unread_filter] = ACTIONS(5),
    [sym_read_filter] = ACTIONS(5),
    [sym_unread_feed] = ACTIONS(7),
    [sym_read_feed] = ACTIONS(7),
    [sym_unread_article] = ACTIONS(5),
    [sym_read_article] = ACTIONS(5),
    [anon_sym_Feed] = ACTIONS(9),
    [anon_sym_Title] = ACTIONS(9),
    [anon_sym_Author] = ACTIONS(9),
    [anon_sym_Date] = ACTIONS(9),
    [anon_sym_Link] = ACTIONS(9),
    [sym_body_start] = ACTIONS(11),
  },
  [STATE(2)] = {
    [sym__element] = STATE(3),
    [sym__filter] = STATE(3),
    [sym__feed] = STATE(3),
    [sym__article] = STATE(3),
    [sym_header] = STATE(3),
    [sym__header_line] = STATE(4),
    [sym__header_key] = STATE(9),
    [sym_body] = STATE(3),
    [aux_sym_nvimboat_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(13),
    [sym_unread_filter] = ACTIONS(15),
    [sym_read_filter] = ACTIONS(15),
    [sym_unread_feed] = ACTIONS(17),
    [sym_read_feed] = ACTIONS(17),
    [sym_unread_article] = ACTIONS(15),
    [sym_read_article] = ACTIONS(15),
    [anon_sym_Feed] = ACTIONS(9),
    [anon_sym_Title] = ACTIONS(9),
    [anon_sym_Author] = ACTIONS(9),
    [anon_sym_Date] = ACTIONS(9),
    [anon_sym_Link] = ACTIONS(9),
    [sym_body_start] = ACTIONS(11),
  },
  [STATE(3)] = {
    [sym__element] = STATE(3),
    [sym__filter] = STATE(3),
    [sym__feed] = STATE(3),
    [sym__article] = STATE(3),
    [sym_header] = STATE(3),
    [sym__header_line] = STATE(4),
    [sym__header_key] = STATE(9),
    [sym_body] = STATE(3),
    [aux_sym_nvimboat_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(19),
    [sym_unread_filter] = ACTIONS(21),
    [sym_read_filter] = ACTIONS(21),
    [sym_unread_feed] = ACTIONS(24),
    [sym_read_feed] = ACTIONS(24),
    [sym_unread_article] = ACTIONS(21),
    [sym_read_article] = ACTIONS(21),
    [anon_sym_Feed] = ACTIONS(27),
    [anon_sym_Title] = ACTIONS(27),
    [anon_sym_Author] = ACTIONS(27),
    [anon_sym_Date] = ACTIONS(27),
    [anon_sym_Link] = ACTIONS(27),
    [sym_body_start] = ACTIONS(30),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(35), 2,
      sym_unread_feed,
      sym_read_feed,
    ACTIONS(33), 11,
      ts_builtin_sym_end,
      sym_unread_filter,
      sym_read_filter,
      sym_unread_article,
      sym_read_article,
      anon_sym_Feed,
      anon_sym_Title,
      anon_sym_Author,
      anon_sym_Date,
      anon_sym_Link,
      sym_body_start,
  [18] = 2,
    ACTIONS(39), 2,
      sym_unread_feed,
      sym_read_feed,
    ACTIONS(37), 11,
      ts_builtin_sym_end,
      sym_unread_filter,
      sym_read_filter,
      sym_unread_article,
      sym_read_article,
      anon_sym_Feed,
      anon_sym_Title,
      anon_sym_Author,
      anon_sym_Date,
      anon_sym_Link,
      sym_body_start,
  [36] = 2,
    ACTIONS(43), 2,
      sym_unread_feed,
      sym_read_feed,
    ACTIONS(41), 11,
      ts_builtin_sym_end,
      sym_unread_filter,
      sym_read_filter,
      sym_unread_article,
      sym_read_article,
      anon_sym_Feed,
      anon_sym_Title,
      anon_sym_Author,
      anon_sym_Date,
      anon_sym_Link,
      sym_body_start,
  [54] = 1,
    ACTIONS(45), 1,
      sym_content,
  [58] = 1,
    ACTIONS(47), 1,
      ts_builtin_sym_end,
  [62] = 1,
    ACTIONS(49), 1,
      anon_sym_COLON,
  [66] = 1,
    ACTIONS(51), 1,
      sym__expression,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 18,
  [SMALL_STATE(6)] = 36,
  [SMALL_STATE(7)] = 54,
  [SMALL_STATE(8)] = 58,
  [SMALL_STATE(9)] = 62,
  [SMALL_STATE(10)] = 66,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nvimboat, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nvimboat, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_nvimboat_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_nvimboat_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [24] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_nvimboat_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_nvimboat_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_nvimboat_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 1, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header, 1, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 2, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_body, 2, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__header_line, 3, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__header_line, 3, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [47] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_nvimboat(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "nvimboat",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
