// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package rssdb

import (
	"database/sql"
)

type GoogleReplay struct {
	ID    int64
	Guid  string
	State int64
	Ts    int64
}

type Metadatum struct {
	DbSchemaVersionMajor int64
	DbSchemaVersionMinor int64
}

type RssFeed struct {
	Rssurl       string
	Url          string
	Title        string
	Lastmodified interface{}
	IsRtl        interface{}
	Etag         string
}

type RssItem struct {
	ID                           int64
	Guid                         string
	Title                        string
	Author                       string
	Url                          string
	Feedurl                      string
	Pubdate                      int64
	Content                      string
	Unread                       interface{}
	EnclosureUrl                 sql.NullString
	EnclosureType                sql.NullString
	Enqueued                     interface{}
	Flags                        sql.NullString
	Deleted                      interface{}
	Base                         string
	ContentMimeType              string
	EnclosureDescription         string
	EnclosureDescriptionMimeType string
}

type SqliteSequence struct {
	Name interface{}
	Seq  interface{}
}

type SqliteStat1 struct {
	Tbl  interface{}
	Idx  interface{}
	Stat interface{}
}
