// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package rssdb

import (
	"context"
	"database/sql"
	"strings"
)

const addArticle = `-- name: AddArticle :exec
INSERT INTO rss_item (
	guid, title, author, url, feedurl, pubDate, content, unread, enclosure_url, flags, content_mime_type
	) VALUES (
	?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type AddArticleParams struct {
	Guid            string
	Title           string
	Author          string
	Url             string
	Feedurl         string
	Pubdate         int64
	Content         string
	Unread          int
	EnclosureUrl    sql.NullString
	Flags           sql.NullString
	ContentMimeType string
}

func (q *Queries) AddArticle(ctx context.Context, arg AddArticleParams) error {
	_, err := q.db.ExecContext(ctx, addArticle,
		arg.Guid,
		arg.Title,
		arg.Author,
		arg.Url,
		arg.Feedurl,
		arg.Pubdate,
		arg.Content,
		arg.Unread,
		arg.EnclosureUrl,
		arg.Flags,
		arg.ContentMimeType,
	)
	return err
}

const cleanupDeleted = `-- name: CleanupDeleted :exec
DELETE FROM rss_item
WHERE deleted = 1
`

func (q *Queries) CleanupDeleted(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cleanupDeleted)
	return err
}

const createFeed = `-- name: CreateFeed :one
INSERT INTO rss_feed (
	rssurl, url, title
	) VALUES (
	?, ?, ?
	)
RETURNING rssurl, url, title, lastmodified, is_rtl, etag
`

type CreateFeedParams struct {
	Rssurl string
	Url    string
	Title  string
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (RssFeed, error) {
	row := q.db.QueryRowContext(ctx, createFeed, arg.Rssurl, arg.Url, arg.Title)
	var i RssFeed
	err := row.Scan(
		&i.Rssurl,
		&i.Url,
		&i.Title,
		&i.Lastmodified,
		&i.IsRtl,
		&i.Etag,
	)
	return i, err
}

const deleteArticles = `-- name: DeleteArticles :exec
UPDATE rss_item
SET deleted = 1
WHERE url IN (/*SLICE:url*/?)
`

func (q *Queries) DeleteArticles(ctx context.Context, url []string) error {
	query := deleteArticles
	var queryParams []interface{}
	if len(url) > 0 {
		for _, v := range url {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:url*/?", strings.Repeat(",?", len(url))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:url*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const deleteFeedArticles = `-- name: DeleteFeedArticles :exec
UPDATE rss_item
SET deleted = 1
WHERE feedurl IN (/*SLICE:feedurl*/?)
`

func (q *Queries) DeleteFeedArticles(ctx context.Context, feedurl []string) error {
	query := deleteFeedArticles
	var queryParams []interface{}
	if len(feedurl) > 0 {
		for _, v := range feedurl {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:feedurl*/?", strings.Repeat(",?", len(feedurl))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:feedurl*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const getArticle = `-- name: GetArticle :one
SELECT guid, title, author, url, feedurl, pubDate, content, unread FROM rss_item
WHERE url = ? LIMIT 1
`

type GetArticleRow struct {
	Guid    string
	Title   string
	Author  string
	Url     string
	Feedurl string
	Pubdate int64
	Content string
	Unread  int
}

func (q *Queries) GetArticle(ctx context.Context, url string) (GetArticleRow, error) {
	row := q.db.QueryRowContext(ctx, getArticle, url)
	var i GetArticleRow
	err := row.Scan(
		&i.Guid,
		&i.Title,
		&i.Author,
		&i.Url,
		&i.Feedurl,
		&i.Pubdate,
		&i.Content,
		&i.Unread,
	)
	return i, err
}

const getFeed = `-- name: GetFeed :one
SELECT rssurl, url, title, lastmodified, is_rtl, etag FROM rss_feed
WHERE rssurl = ? LIMIT 1
`

func (q *Queries) GetFeed(ctx context.Context, rssurl string) (RssFeed, error) {
	row := q.db.QueryRowContext(ctx, getFeed, rssurl)
	var i RssFeed
	err := row.Scan(
		&i.Rssurl,
		&i.Url,
		&i.Title,
		&i.Lastmodified,
		&i.IsRtl,
		&i.Etag,
	)
	return i, err
}

const getFeedPage = `-- name: GetFeedPage :many
SELECT unread, pubDate, author, title, url FROM rss_item
WHERE feedurl = ?
AND deleted = 0
ORDER BY pubDate DESC
`

type GetFeedPageRow struct {
	Unread  int
	Pubdate int64
	Author  string
	Title   string
	Url     string
}

func (q *Queries) GetFeedPage(ctx context.Context, feedurl string) ([]GetFeedPageRow, error) {
	rows, err := q.db.QueryContext(ctx, getFeedPage, feedurl)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFeedPageRow
	for rows.Next() {
		var i GetFeedPageRow
		if err := rows.Scan(
			&i.Unread,
			&i.Pubdate,
			&i.Author,
			&i.Title,
			&i.Url,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryFilter = `-- name: QueryFilter :many
SELECT guid, title, author, url, feedurl, pubDate, content, unread FROM rss_item
WHERE guid LIKE ?
AND title LIKE ?
AND author LIKE ?
AND url LIKE ?
AND feedurl IN (/*SLICE:feedurls*/?)
AND content LIKE ?
AND unread IN (/*SLICE:unread_states*/?)
AND content_mime_type LIKE ?
AND deleted = 0
ORDER BY pubDate DESC
`

type QueryFilterParams struct {
	Guid            string
	Title           string
	Author          string
	Url             string
	Feedurls        []string
	Content         string
	UnreadStates    []int
	ContentMimeType string
}

type QueryFilterRow struct {
	Guid    string
	Title   string
	Author  string
	Url     string
	Feedurl string
	Pubdate int64
	Content string
	Unread  int
}

func (q *Queries) QueryFilter(ctx context.Context, arg QueryFilterParams) ([]QueryFilterRow, error) {
	query := queryFilter
	var queryParams []interface{}
	queryParams = append(queryParams, arg.Guid)
	queryParams = append(queryParams, arg.Title)
	queryParams = append(queryParams, arg.Author)
	queryParams = append(queryParams, arg.Url)
	if len(arg.Feedurls) > 0 {
		for _, v := range arg.Feedurls {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:feedurls*/?", strings.Repeat(",?", len(arg.Feedurls))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:feedurls*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.Content)
	if len(arg.UnreadStates) > 0 {
		for _, v := range arg.UnreadStates {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:unread_states*/?", strings.Repeat(",?", len(arg.UnreadStates))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:unread_states*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.ContentMimeType)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryFilterRow
	for rows.Next() {
		var i QueryFilterRow
		if err := rows.Scan(
			&i.Guid,
			&i.Title,
			&i.Author,
			&i.Url,
			&i.Feedurl,
			&i.Pubdate,
			&i.Content,
			&i.Unread,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryMainPage = `-- name: QueryMainPage :many
SELECT 
	rss_feed.title,
	feed_articles.feedurl, feed_articles.unread_count, feed_articles.article_count
FROM rss_feed
LEFT JOIN (
	SELECT feedurl,
		CAST(SUM(unread) AS INTEGER) AS unread_count,
		COUNT(*) AS article_count
	FROM rss_item WHERE deleted = 0
	GROUP BY feedurl
) feed_articles
ON rss_feed.rssurl = feed_articles.feedurl
ORDER BY rss_feed.title
`

type QueryMainPageRow struct {
	Title        string
	Feedurl      string
	UnreadCount  int64
	ArticleCount int64
}

func (q *Queries) QueryMainPage(ctx context.Context) ([]QueryMainPageRow, error) {
	rows, err := q.db.QueryContext(ctx, queryMainPage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryMainPageRow
	for rows.Next() {
		var i QueryMainPageRow
		if err := rows.Scan(
			&i.Title,
			&i.Feedurl,
			&i.UnreadCount,
			&i.ArticleCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryTagFeeds = `-- name: QueryTagFeeds :many
SELECT
	f.title,
	f.rssurl AS feedurl,
	CAST(SUM(i.unread) AS INTEGER) AS unread_count,
	COUNT(*) AS article_count
FROM rss_feed f
LEFT JOIN rss_item i
ON f.rssurl = i.feedurl AND i.deleted = 0
WHERE f.rssurl IN (/*SLICE:feedurls*/?)
GROUP BY f.title, f.rssurl
ORDER BY f.title
`

type QueryTagFeedsRow struct {
	Title        string
	Feedurl      string
	UnreadCount  int64
	ArticleCount int64
}

func (q *Queries) QueryTagFeeds(ctx context.Context, feedurls []string) ([]QueryTagFeedsRow, error) {
	query := queryTagFeeds
	var queryParams []interface{}
	if len(feedurls) > 0 {
		for _, v := range feedurls {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:feedurls*/?", strings.Repeat(",?", len(feedurls))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:feedurls*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryTagFeedsRow
	for rows.Next() {
		var i QueryTagFeedsRow
		if err := rows.Scan(
			&i.Title,
			&i.Feedurl,
			&i.UnreadCount,
			&i.ArticleCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setArticlesRead = `-- name: SetArticlesRead :exec
UPDATE rss_item
SET unread = 0
WHERE url IN (/*SLICE:url*/?)
`

func (q *Queries) SetArticlesRead(ctx context.Context, url []string) error {
	query := setArticlesRead
	var queryParams []interface{}
	if len(url) > 0 {
		for _, v := range url {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:url*/?", strings.Repeat(",?", len(url))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:url*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const setArticlesUnread = `-- name: SetArticlesUnread :exec
UPDATE rss_item
SET unread = 1
WHERE url IN (/*SLICE:url*/?)
`

func (q *Queries) SetArticlesUnread(ctx context.Context, url []string) error {
	query := setArticlesUnread
	var queryParams []interface{}
	if len(url) > 0 {
		for _, v := range url {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:url*/?", strings.Repeat(",?", len(url))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:url*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const setFeedsRead = `-- name: SetFeedsRead :exec
UPDATE rss_item
SET unread = 0
WHERE feedurl IN (/*SLICE:feedurl*/?)
`

func (q *Queries) SetFeedsRead(ctx context.Context, feedurl []string) error {
	query := setFeedsRead
	var queryParams []interface{}
	if len(feedurl) > 0 {
		for _, v := range feedurl {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:feedurl*/?", strings.Repeat(",?", len(feedurl))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:feedurl*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const setFeedsUnread = `-- name: SetFeedsUnread :exec
UPDATE rss_item
SET unread = 1
WHERE feedurl IN (/*SLICE:feedurl*/?)
`

func (q *Queries) SetFeedsUnread(ctx context.Context, feedurl []string) error {
	query := setFeedsUnread
	var queryParams []interface{}
	if len(feedurl) > 0 {
		for _, v := range feedurl {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:feedurl*/?", strings.Repeat(",?", len(feedurl))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:feedurl*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}
